@startuml
!theme mars

class Entity {
  - {static} enitityID: int
  - faces: ArrayList<Face>
  - id: int
  - objName: String
  - orient: Vector3D
  - pivot: Vector3D
  - vertexCount: int
  + rotate(double): void
  + scale(float): void
  + toString(): String
}
class Face {
  - material: Material
  - smoothingGroup: int
  - vertices: Vertex[]
  + getVertexCount(): int
  + toString(): String
}
class Material {
  - d: float
  - illum: int
  - ka: float[]
  - kd: float[]
  - ke: float[]
  - ks: float[]
  - mapKd: String
  - matName: String
  - ni: float
  - ns: float
  + toString(): String
}
class ObjFileReader {
  - {static} parseToRGB(String[]): float[]
  + {static} createMaterial(String): HashMap<String, Material>
  + {static} createObject(String): Entity
}
class Vector3D {
  - x: float
  - y: float
  - z: float
  + add(Vector3D): Vector3D
  + crossProduct(Vector3D): Vector3D
  + length(): float
  + mul(Vector3D): Vector3D
  + normalize(): Vector3D
  + scalarMultiplication(float): Vector3D
  + scalarProduct(Vector3D): float
  + subtract(Vector3D): Vector3D
  + toString(): String
}
class Vertex {
  - coordinates: Vector3D
  - normal: Vector3D
  - texture: Vector3D
  + toString(): String
}

Entity          "1" -[#595959,plain]->  "faces\n*"          Face
Entity          "1" -[#595959,plain]->  "pivot\n1"          Vector3D
Entity          "1" -[#595959,plain]->  "orient\n1"         Vector3D
Face            "1" -[#595959,plain]->  "material\n1"       Material
Face            "1" -[#595959,plain]->  "vertices\n*"       Vertex
ObjFileReader       -[#595959,dashed]->                     Entity : "«create»"
ObjFileReader       -[#595959,dashed]->                     Material : "«create»"
Vertex          "1" -[#595959,plain]->  "coordinates\n1"    Vector3D
Vertex          "1" -[#595959,plain]->  "normal\n1"         Vector3D
Vertex          "1" -[#595959,plain]->  "texture\n1"        Vector3D
@enduml
